'use client';
import { useState, useEffect, useCallback } from 'react';
import { FeedbackCandidatePanel } from './feedback-candidate-panel';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { csrfHeaders } from '@/lib/auth/csrf-client';
const actions:Record<string,string>={ALLOW:'允许',WARN:'提示',MASK:'脱敏',REWRITE:'改写',SAFE_RESPONSE:'安全替代',REQUIRE_REVIEW:'人工审核',BLOCK:'阻断'};
interface Feedback { id:string; submittedBy:string|null; classification:string; expectedAction:string; status:string; reason:string|null; reviewedBy:string|null; reviewDecision:string|null; reviewReason:string|null }
export function AlertFeedbackPanel({alertId}:{alertId:string}){
 const [classification,setClassification]=useState('WRONG_EXPLANATION'),[expectedAction,setExpectedAction]=useState('REQUIRE_REVIEW'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [items,setItems]=useState<Feedback[]>([]),[reviewId,setReviewId]=useState<string|null>(null),[reviewReason,setReviewReason]=useState(''),[actor,setActor]=useState<{id:string;permissions:string[]}|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const response=await fetch('/api/security-alerts/'+encodeURIComponent(alertId)+'/feedback',{signal,cache:'no-store'});if(!response.ok)throw new Error('复核列表读取失败');const payload=await response.json() as {items:Feedback[]};if(!signal?.aborted)setItems(payload.items);}catch(error:unknown){if(!signal?.aborted)setMessage(error instanceof Error?error.message:'读取失败');}},[alertId]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);void fetch('/api/auth/me',{signal:controller.signal,cache:'no-store'}).then(response=>response.ok?response.json():null).then((data:{user:{id:string;permissions:string[]}}|null)=>{if(!controller.signal.aborted)setActor(data?.user??null);}).catch(()=>undefined);return()=>controller.abort();},[load]);
 async function review(decision:'ACCEPT'|'REJECT'){if(!reviewId)return;setBusy(true);try{const response=await fetch('/api/security-alerts/'+encodeURIComponent(alertId)+'/feedback/review',{method:'POST',headers:{...csrfHeaders(),'content-type':'application/json'},body:JSON.stringify({feedbackId:reviewId,decision,reason:reviewReason})});if(!response.ok)throw new Error('复核失败，需另一名授权人员且记录未被复核');setReviewId(null);setReviewReason('');setMessage(decision==='ACCEPT'?'已确认反馈，进入样例准备阶段，尚未发布策略。':'已驳回反馈并保留复核记录。');await load();}catch(error:unknown){setMessage(error instanceof Error?error.message:'复核失败');}finally{setBusy(false);}}
 async function submit(){setBusy(true);setMessage('');try{const response=await fetch('/api/security-alerts/'+encodeURIComponent(alertId)+'/feedback',{method:'POST',headers:{...csrfHeaders(),'content-type':'application/json'},body:JSON.stringify({classification,expectedAction,reason})});if(!response.ok)throw new Error('反馈提交失败，请检查权限及说明。');setMessage('已进入待复核队列，尚未修改检测策略。');setReason('');await load();}catch(error:unknown){setMessage(error instanceof Error?error.message:'反馈提交失败');}finally{setBusy(false);}}
 return <div className="mt-5 space-y-3 rounded-md border p-4"><h3 className="text-sm font-medium">检测纠错反馈</h3><div className="flex flex-wrap gap-3"><Select value={classification} onValueChange={setClassification}><SelectTrigger className="w-40" aria-label="纠错类型"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="WRONG_EXPLANATION">判定依据待复核</SelectItem><SelectItem value="WRONG_ACTION">处置动作需调整</SelectItem><SelectItem value="FALSE_POSITIVE">疑似误报</SelectItem><SelectItem value="FALSE_NEGATIVE">疑似漏报</SelectItem></SelectContent></Select><Select value={expectedAction} onValueChange={setExpectedAction}><SelectTrigger className="w-40" aria-label="期望动作"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(actions).map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><Textarea aria-label="纠错依据" placeholder="说明业务语境和复核依据，至少 10 个字符；无需复制敏感原文。" value={reason} onChange={event=>setReason(event.target.value)} maxLength={500}/><Button disabled={busy||reason.trim().length<10} onClick={()=>void submit()}>{busy?'提交中…':'提交复核'}</Button>{items.length>0&&<div className="space-y-2"><h4 className="text-sm font-medium">反馈复核记录</h4>{items.map(item=><div key={item.id} className="rounded border p-3 text-sm"><p>{item.classification} · {actions[item.expectedAction]} · {item.status}</p><p className="mt-1 text-muted-foreground">{item.reason}</p>{item.reviewedBy&&<p className="mt-1">复核：{item.reviewDecision==='ACCEPT'?'确认':'驳回'} · {item.reviewReason}</p>}{item.status==='triaged'&&item.reviewDecision==='ACCEPT'&&actor?.permissions.includes('content:raw:read')&&<FeedbackCandidatePanel alertId={alertId} feedbackId={item.id}/>}
{item.status==='open'&&actor?.permissions.includes('audit:approve')&&item.submittedBy!==actor.id&&<Button className="mt-2" variant="outline" size="sm" onClick={()=>setReviewId(item.id)}>复核此反馈</Button>}</div>)}</div>}{reviewId&&<div className="space-y-2 rounded border p-3"><Textarea aria-label="复核意见" placeholder="填写独立复核依据，至少 10 个字符" value={reviewReason} maxLength={500} onChange={event=>setReviewReason(event.target.value)}/><div className="flex gap-2"><Button disabled={busy||reviewReason.trim().length<10} onClick={()=>void review('ACCEPT')}>确认反馈</Button><Button variant="destructive" disabled={busy||reviewReason.trim().length<10} onClick={()=>void review('REJECT')}>驳回</Button><Button variant="ghost" onClick={()=>setReviewId(null)}>取消</Button></div><p className="text-xs text-muted-foreground">反馈复核不代表金标审批或策略发布。</p></div>}{message&&<p role="status" className="text-sm">{message}</p>}</div>;
}
