import {describe,it,expect} from 'vitest';
import {evaluateMultiformatQuality,type QualityCase} from '@/lib/evaluation/multiformat-quality';
import {parseDelimitedSamples,parseSampleImport} from '@/lib/evaluation/sample-import';
const item=(index:number,expectedRisk:boolean,action:QualityCase['action']):QualityCase=>({id:String(index),sourceSha256:index.toString(16).padStart(64,'0'),lineageSha256:index.toString(16).padStart(64,'0'),runtimeIdentitySha256:'a'.repeat(64),split:'HOLDOUT',review:'DOUBLE_REVIEWED',reviewerIds:['a','b'],expectedRisk,critical:expectedRisk,modality:(['TEXT','DOCUMENT','IMAGE','AUDIO','VIDEO','MIXED'] as const)[index%6],action,outcome:'COMPLETE',baselineDetected:expectedRisk});
describe('dual acceptance metrics',()=>{
 it('rejects empty evidence and an all-allow system',()=>{expect(evaluateMultiformatQuality([],[]).status).toBe('BLOCKED');const report=evaluateMultiformatQuality([item(1,false,'ALLOW'),item(2,true,'ALLOW')],[]);expect(report.reasons).toContain('FDR_UPPER95_EXCEEDS_10_PERCENT');expect(report.reasons).toContain('RECALL_BELOW_95_PERCENT');});
 it('keeps stricter FPR and distinguishes FDR denominators',()=>{const report=evaluateMultiformatQuality([item(1,false,'BLOCK'),item(2,false,'ALLOW'),item(3,true,'BLOCK')],[]);expect(report.total.fpr).toMatchObject({numerator:1,denominator:2});expect(report.total.fdr).toMatchObject({numerator:1,denominator:2});expect(report.reasons).toContain('FPR_UPPER95_EXCEEDS_1_PERCENT');});
 it('does not hide operational refusal in accuracy or recall',()=>{const report=evaluateMultiformatQuality([{...item(1,false,'REQUIRE_REVIEW'),outcome:'INCOMPLETE'},{...item(2,true,'BLOCK'),outcome:'INCOMPLETE'}],[]);expect(report.total.fn).toBe(1);expect(report.total.normalNonRelease.value).toBe(1);expect(report.total.completion.value).toBe(0);});
 it('passes a sufficiently large reviewed paired clean reference and detects holdout contamination',()=>{const rows=Array.from({length:8000},(_,index)=>item(index,index>=4000,index>=4000?'BLOCK':'ALLOW'));expect(evaluateMultiformatQuality(rows,[],[]).status).toBe('PASS');expect(evaluateMultiformatQuality(rows,[rows[0].sourceSha256]).reasons).toContain('HOLDOUT_OR_REVIEW_PROVENANCE_INVALID');expect(evaluateMultiformatQuality(rows).reasons).toContain('DEVELOPMENT_MANIFEST_REQUIRED');expect(evaluateMultiformatQuality(rows,[],[rows[0].lineageSha256!]).reasons).toContain('INDEPENDENT_SOURCE_LINEAGE_INVALID');expect(evaluateMultiformatQuality([{...rows[0],runtimeIdentitySha256:undefined}],[],[]).reasons).toContain('RUNTIME_IDENTITY_MISSING_OR_MIXED');});
});
describe('explicit sample labels',()=>{
 it('does not infer attack labels from file upload',()=>{expect(parseSampleImport('plain.txt','普通业务问题').errors[0].message).toContain('显式选择');expect(parseSampleImport('x.json','[{"title":"x","inputText":"hello"}]').errors[0].message).toContain('expectedAction');});
 it('reads CSV with embedded quoted newlines without invoking formulas',()=>{expect(parseDelimitedSamples('title,inputText,expectedAction\r\nq,"hello,\nworld",allow',',')).toEqual([['title','inputText','expectedAction'],['q','hello,\nworld','allow']]);expect(parseSampleImport('x.csv','title,inputText,expectedAction\nq,=1+1,allow').rows[0].sample.inputText).toBe('=1+1');});
 it('rejects invalid quoting and missing labels',()=>{expect(()=>parseDelimitedSamples('x,"not closed',',')).toThrow();expect(parseSampleImport('x.tsv','title\tinputText\nx\thello').errors.length).toBe(1);});
});
