import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {eq} from 'drizzle-orm';
import {NextRequest} from 'next/server';
import {db} from '@/storage/database/shared/db';
import {applications,archivedContentObjects,conversationArchives} from '@/storage/database/shared/schema';
import {captureModelRouting,mappedModelRequest} from '@/lib/gateway-runtime/model-routing';
import {authorizeGateway} from '@/lib/gateway-runtime/authorization';
import {issueConsoleAssertion} from '@/lib/gateway-runtime/security';
import {canonicalJson,sha256,type JsonValue} from '@/lib/gateway-runtime/protocol';
import {evaluateGateway} from '@/lib/gateway-runtime/evaluation';
import {recordGatewayEvents} from '@/lib/gateway-runtime/events';
import {recordGatewayArchive} from '@/lib/conversation-archive/gateway';
import {readArchivedContent} from '@/lib/conversation-archive/service';
import type {TenantScope} from '@/lib/tenancy';
type GatewayRequest = Parameters<typeof evaluateGateway>[0];
export async function exerciseDerivedGateway(input:TenantScope&{ownerId:string;jobId:string;request:Record<string,JsonValue>;references:Array<{artifactId:string;sha256:string}>;adapter:Record<string,unknown>},check:(id:string)=>void){
 const [app]=await db.select().from(applications).where(eq(applications.id,input.applicationId));assert.ok(app);
 const alias=String(input.request.model),id=randomUUID(),scope={tenantId:input.tenantId,applicationId:input.applicationId};
 await db.update(applications).set({modelRoutes:[alias],authVersion:app.authVersion+1}).where(eq(applications.id,app.id));
 process.env.MODEL_BASE_URL='https://model.invalid';
 process.env.GUARD_MODEL_ROUTES_JSON=JSON.stringify([{id:alias,baseUrl:'https://model.invalid',weight:100,targetModel:'synthetic-target-1'}]);
 process.env.GATEWAY_MODEL_ROUTE_BOUNDARIES_JSON=JSON.stringify({[alias]:[app.dataClass]});
 const routing=captureModelRouting([alias],app.dataClass);
 const adapter={...input.adapter,routingDigest:routing.configurationDigest};
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON=JSON.stringify([adapter]);
 const request={...input.request,guard_artifacts:input.references.map(ref=>({...ref,jobId:input.jobId,representation:'TEXT_PROJECTION'}))},raw=canonicalJson(request);
 const body={contractVersion:'2.0' as const,businessRequestId:id,traceId:id,idempotencyKey:id,deadline:Date.now()+59000,modelRoute:alias,requestDigest:sha256(raw),requestJson:raw,
 userAssertion:issueConsoleAssertion({...scope,subject:input.ownerId,tokenVersion:0,authenticationMethod:'bearer',roles:['SYSTEM_ADMIN'],permissions:['guard:use']},sha256(raw))};
 const authorization=await authorizeGateway(body,new NextRequest('http://gateway.internal/authorize'));
 assert.ok(authorization.preparedRequestJson);assert.ok(authorization.inputSegments);assert.equal(authorization.inputSegments.filter(segment=>segment.sourceType==='FILE').length,2);
 const [archive]=await db.select().from(conversationArchives).where(eq(conversationArchives.requestId,id));assert.equal(archive.mediaComplete,true);check('GATEWAY_AUTHORIZATION_ARCHIVES_DERIVED_PROVENANCE');
 const step:GatewayRequest={contractVersion:'2.0',auth:authorization.auth,businessRequestId:id,stepId:randomUUID(),traceId:id,stage:'INPUT',streamSeq:0,attemptKind:'INITIAL',snapshotId:authorization.snapshot.id,deadline:body.deadline,segments:authorization.inputSegments};
 const decision=await evaluateGateway(step,AbortSignal.timeout(20000));assert.equal(decision.status,'SUCCEEDED');assert.equal(decision.coverage,'COMPLETE');assert.ok(['ALLOW','WARN'].includes(decision.action));check('REAL_GATEWAY_RECHECKS_FULL_PROJECTED_INPUT');
 await assert.rejects(evaluateGateway({...step,stepId:randomUUID(),stage:'INPUT_RECHECK',attemptKind:'RECHECK'},AbortSignal.timeout(20000)),/DERIVED_INPUT_RECHECK_REQUIRES_NEW_JOB/);check('PROJECTED_INPUT_REWRITE_REQUIRES_NEW_ANALYSIS');
 const rangeEnd=step.segments.reduce((sum,segment)=>sum+segment.text.length,0),payloadDigest=sha256(canonicalJson(step.segments));
 const event={eventSeq:1,kind:'UPSTREAM_SEND_INTENT' as const,stepId:step.stepId,decisionId:decision.decisionId,snapshotId:step.snapshotId,actualAction:decision.action,payloadDigest,rangeStart:0,rangeEnd};
 await assert.rejects(recordGatewayEvents({contractVersion:'2.0',auth:authorization.auth,events:[event]}),/ARCHIVE_EXECUTION_CONTENT_NOT_COMMITTED/);check('SEND_INTENT_REQUIRES_DURABLE_MODEL_INPUT');
 const modelRequest=mappedModelRequest(JSON.parse(authorization.preparedRequestJson),routing.configurationJson,authorization.auth.context);
 const content={contractVersion:'2.0' as const,auth:authorization.auth,purpose:'MODEL_INPUT' as const,sequence:0,representation:'REQUEST_JSON' as const,contentJson:canonicalJson(modelRequest),sourceStepId:step.stepId,eventSequence:1,payloadDigest,rangeStart:0,rangeEnd};
 assert.ok(modelRequest&&typeof modelRequest==='object'&&!Array.isArray(modelRequest));
 await assert.rejects(recordGatewayArchive({...content,contentJson:canonicalJson({...modelRequest,model:'tampered-target'})}),/ARCHIVE_.*MISMATCH/);check('TARGET_MODEL_WIRE_TAMPER_REJECTED');
 await recordGatewayArchive(content,AbortSignal.timeout(15000));
 const objects=await db.select().from(archivedContentObjects).where(eq(archivedContentObjects.requestId,id));
 const original=objects.find(object=>object.purpose==='MODEL_INPUT');assert.ok(original);assert.equal(original.state,'MANIFEST_COMMITTED');
 const restored=await readArchivedContent(scope,original.id);assert.deepEqual(restored.content,modelRequest);check('EXACT_TARGET_MODEL_WIRE_ENCRYPTED_AND_READ_BACK');
 assert.equal((await recordGatewayEvents({contractVersion:'2.0',auth:authorization.auth,events:[event]})).state,'SEND_INTENT');check('SIGNED_REQUEST_RECEIVES_SEND_INTENT_AFTER_CHECKS');
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON='[]';
 await assert.rejects(recordGatewayEvents({contractVersion:'2.0',auth:authorization.auth,events:[{eventSeq:2,kind:'UPSTREAM_SEND_STARTED',snapshotId:step.snapshotId}]}),/NOT_QUALIFIED/);check('ADAPTER_REVOCATION_BEFORE_SEND_START_REJECTED');
 await recordGatewayEvents({contractVersion:'2.0',auth:authorization.auth,events:[{eventSeq:2,kind:'TERMINATED',snapshotId:step.snapshotId,reasonCode:'SYNTHETIC_CONTROL_PLANE_TEST_NO_UPSTREAM'}]});
 await db.update(applications).set({modelRoutes:app.modelRoutes}).where(eq(applications.id,app.id));
}
