import assert from 'node:assert/strict';
import {exerciseDerivedGateway} from './derived-gateway';
import {randomUUID,generateKeyPairSync} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {eq} from 'drizzle-orm';
import {db,closeDatabaseConnection} from '@/storage/database/shared/db';
import {artifacts,guardJobs} from '@/storage/database/shared/schema';
import {storeVerifiedBytes} from '@/lib/artifacts/server-upload';
import {submitGuardJob} from '@/lib/guard-jobs';
import {processNextIntakeJob} from '@/lib/media/intake-worker';
import {prepareDerivedExecution} from '@/lib/gateway-runtime/derived-execution';
import {assertArtifactContextActive,materializeArtifactRequest,type ArtifactContextProof} from '@/lib/gateway-runtime/artifact-context';
import {signPayload} from '@/lib/gateway-runtime/security';
import {canonicalJson,extractSegments,sha256,type JsonValue} from '@/lib/gateway-runtime/protocol';
import {loadVerifiedPolicyBundle} from '@/lib/policy-bundle';
const out=resolve(process.env.COMPREHENSIVE_RUN_DIR!);
const f=JSON.parse(readFileSync(out+'/fixture.private.json','utf8')) as {tenantId:string;applicationId:string;userId:string;bundleId:string;other:{userId:string};foreign:{tenantId:string;applicationId:string}};
const scope={tenantId:f.tenantId,applicationId:f.applicationId},ownerId=f.userId;
const checks:Array<{id:string;status:'PASS'}>=[],check=(id:string)=>{checks.push({id,status:'PASS'});console.log(id+' PASS');};
async function main(){
 const url=new URL(process.env.DATABASE_URL!);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'5438');assert.match(url.pathname,/^\/guardllm_integration_full_\d+$/);
 const keys=generateKeyPairSync('ed25519');
 process.env.GATEWAY_AUTH_KEY_ID='derived-chat-engineering-only';
 process.env.GATEWAY_AUTH_SIGNING_PRIVATE_KEY=keys.privateKey.export({type:'pkcs8',format:'pem'}).toString();
 process.env.GATEWAY_AUTH_PUBLIC_KEYS_JSON=JSON.stringify({[process.env.GATEWAY_AUTH_KEY_ID]:keys.publicKey.export({type:'spki',format:'pem'}).toString()});
 const texts=['The public library opens at nine.','Visitors may borrow books for two weeks.'];
 const parents=await Promise.all(texts.map((text,index)=>storeVerifiedBytes({scope,ownerId,kind:'TEXT',fileName:'source-'+index+'.txt',mediaType:'text/plain',bytes:Buffer.from(text)})));
 const request:Record<string,JsonValue>={model:'engineering-only-route',messages:[{role:'system',content:'Answer with the provided context.'},{role:'user',content:'a'.repeat(4200)+' Summarize these files.'}],stream:false};
 const raw=canonicalJson(request),context=await storeVerifiedBytes({scope,ownerId,kind:'TEXT',fileName:'chat-context.json',mediaType:'application/json',bytes:Buffer.from(raw)});
 const submission={scope,ownerId,artifactId:parents[0].id,sourceArtifactIds:parents.map(p=>p.id),contextArtifactId:context.id,bundleId:f.bundleId,taskPurpose:'Summarize these files.',jobType:'intake',idempotencyKey:randomUUID(),maxAttempts:1};
 const submitted=await submitGuardJob(submission);assert.deepEqual(await processNextIntakeJob(),{jobId:submitted.job.id,status:'completed'});
 const [job]=await db.select().from(guardJobs).where(eq(guardJobs.id,submitted.job.id));
 assert.equal(job.result?.contextDigest,sha256(raw));assert.equal(job.result?.operationalOutcome,'COMPLETE');check('FULL_CONTEXT_REAL_INTAKE_BOUND');
 assert.equal((await submitGuardJob(submission)).job.id,job.id);check('CONTEXT_BOUND_SUBMISSION_IDEMPOTENT');
 const changedContext=await storeVerifiedBytes({scope,ownerId,kind:'TEXT',fileName:'chat-context-2.json',mediaType:'application/json',bytes:Buffer.from(raw.replace('Summarize','Compare'))});
 await assert.rejects(submitGuardJob({...submission,contextArtifactId:changedContext.id}),/Idempotency/);check('CHANGED_CONTEXT_IDEMPOTENCY_CONFLICT');
 const refs=parents.map(p=>({artifactId:p.id,sha256:p.verifiedSha256!}));
 const input={...scope,subjectId:ownerId,bundleId:f.bundleId,jobId:job.id,contextDigest:sha256(raw),modelRoute:'engineering-only-route',routingDigest:'7'.repeat(64),references:refs,signal:AbortSignal.timeout(120000)};
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON='[]';await assert.rejects(prepareDerivedExecution(input),/NOT_QUALIFIED/);check('UNCONFIGURED_ROUTE_DENIED');
 const bundle=await loadVerifiedPolicyBundle(scope,f.bundleId);
 const adapter={...scope,modelRoute:input.modelRoute,routingDigest:input.routingDigest,bundleDigest:sha256(canonicalJson(bundle.payload)),formatVersion:'chat-text-projection-1',profiles:[{kind:'TEXT',extension:'txt',mediaType:'text/plain',transformVersion:'text-decoder-1:utf-8'}],maximumBytes:1048576,validUntil:'2099-01-01T00:00:00.000Z',approvalRef:'SYNTHETIC_ENGINEERING_ONLY_NO_MEDIA_QUALIFICATION'};
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON=JSON.stringify([adapter]);
 const prepared=await prepareDerivedExecution(input);assert.equal(prepared.proof.requestDigest,sha256(canonicalJson(prepared.request)));
 const messages=prepared.request.messages;assert.ok(Array.isArray(messages));assert.equal(messages.length,4);assert.deepEqual(messages[0],(request.messages as JsonValue[])[0]);assert.deepEqual(messages[3],(request.messages as JsonValue[])[1]);
 for(const [index,text] of texts.entries()){const message=messages[index+1] as {content:string};const content=JSON.parse(message.content) as {text:string;instructionCapability:string;nativeCoverageClaimed:boolean;parentArtifactId:string};
  assert.equal(content.text,text);assert.equal(content.instructionCapability,'FORBIDDEN');assert.equal(content.nativeCoverageClaimed,false);assert.equal(content.parentArtifactId,parents[index].id);}
 check('EXACT_TEXT_WIRE_ORDER_AND_SOURCE_PROVENANCE');
 await assert.rejects(prepareDerivedExecution({...input,contextDigest:sha256(raw.replace('Summarize','Compare'))}),/CONTEXT_MISMATCH/);check('PROMPT_CHANGE_AFTER_4096_CHARS_REJECTED');
 await assert.rejects(prepareDerivedExecution({...input,references:[...refs].reverse()}),/ORDER_MISMATCH/);
 await assert.rejects(prepareDerivedExecution({...input,references:[{...refs[0],sha256:'0'.repeat(64)},refs[1]]}),/ORDER_MISMATCH/);check('REORDERED_OR_REPLACED_ATTACHMENTS_REJECTED');
 await assert.rejects(prepareDerivedExecution({...input,subjectId:f.other.userId}),/JOB_UNAVAILABLE/);
 await assert.rejects(prepareDerivedExecution({...input,...f.foreign}),/JOB_UNAVAILABLE/);check('OWNER_AND_TENANT_ISOLATION');
 await assert.rejects(prepareDerivedExecution({...input,modelRoute:'different-model'}),/NOT_QUALIFIED/);
 await assert.rejects(prepareDerivedExecution({...input,routingDigest:'8'.repeat(64)}),/NOT_QUALIFIED/);check('MODEL_AND_ROUTING_CHANGE_REJECTED');
 const requestId=randomUUID(),manifest:ArtifactContextProof['manifest']={version:'1.0',...scope,subjectId:ownerId,requestId,bundleId:f.bundleId,issuedAt:Date.now(),expiresAt:Date.now()+120000,
  references:prepared.references.map(ref=>({...ref,jobId:job.id,representation:'TEXT_PROJECTION'})),derivedExecution:prepared.proof};
 const proof={manifest,...signPayload('gateway-artifact-context-v1',manifest)},contextInput={...scope,subjectId:ownerId,requestId,bundleId:f.bundleId};
 await assertArtifactContextActive(proof,contextInput);check('SIGNED_PROJECTION_PROOF_REVALIDATES_REAL_OBJECTS');
 await assert.rejects(assertArtifactContextActive({...proof,manifest:{...manifest,requestId:randomUUID()}},contextInput));check('SIGNED_PROOF_TAMPER_REJECTED');
 await assert.rejects(materializeArtifactRequest({...contextInput,request,sourceSegments:extractSegments(request,'INPUT',100000),references:manifest.references,deadline:manifest.expiresAt,maxInputChars:100000,signal:input.signal,archiveRequired:false}),/ARCHIVE_REQUIRED/);check('MANDATORY_ARCHIVE_CANNOT_BE_BYPASSED');
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON='[]';await assert.rejects(assertArtifactContextActive(proof,contextInput),/NOT_QUALIFIED/);
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON=JSON.stringify([adapter]);check('LIVE_ADAPTER_REVOCATION_RECHECKED');
 const asset=prepared.proof.sources[0],originalResult=job.result;
 await db.update(guardJobs).set({result:{...originalResult,normalizedAssets:prepared.proof.sources.map((source,index)=>index?source:{...source,transformVersion:'changed-parser'})}}).where(eq(guardJobs.id,job.id));
 await assert.rejects(assertArtifactContextActive(proof,contextInput),/NOT_QUALIFIED/);
 await db.update(guardJobs).set({result:originalResult}).where(eq(guardJobs.id,job.id));check('TRANSFORM_VERSION_DRIFT_REJECTED');
 await db.update(artifacts).set({state:'quarantined'}).where(eq(artifacts.id,parents[0].id));await assert.rejects(assertArtifactContextActive(proof,contextInput));
 await db.update(artifacts).set({state:'accepted'}).where(eq(artifacts.id,parents[0].id));check('ORIGINAL_REVOCATION_RECHECKED');
 await db.update(artifacts).set({verifiedSha256:'0'.repeat(64)}).where(eq(artifacts.id,asset.artifactId));await assert.rejects(assertArtifactContextActive(proof,contextInput),/SOURCE_CHANGED/);
 await db.update(artifacts).set({verifiedSha256:asset.sha256}).where(eq(artifacts.id,asset.artifactId));check('CHILD_DIGEST_CHANGE_REJECTED');
 await db.update(guardJobs).set({completedAt:new Date(Date.now()-600001)}).where(eq(guardJobs.id,job.id));await assert.rejects(assertArtifactContextActive(proof,contextInput),/JOB_UNAVAILABLE/);
 await db.update(guardJobs).set({completedAt:job.completedAt}).where(eq(guardJobs.id,job.id));check('STALE_JOB_CANNOT_RELEASE');
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON=JSON.stringify([{...adapter,maximumBytes:64}]);await assert.rejects(prepareDerivedExecution(input),/BUDGET_EXCEEDED/);
 process.env.DERIVED_MEDIA_ROUTE_ADAPTERS_JSON=JSON.stringify([adapter]);check('TARGET_WIRE_BUDGET_ENFORCED');
 await db.update(guardJobs).set({result:{...originalResult,degraded:true,operationalOutcome:'INCOMPLETE'}}).where(eq(guardJobs.id,job.id));await assert.rejects(prepareDerivedExecution(input),/REQUIRES_REVIEW/);
 await db.update(guardJobs).set({result:originalResult}).where(eq(guardJobs.id,job.id));check('INCOMPLETE_DETECTION_CANNOT_RELEASE');
 await assertArtifactContextActive(proof,contextInput);
 await exerciseDerivedGateway({...scope,ownerId,jobId:job.id,request,references:refs,adapter},check);
 writeFileSync(out+'/derived-chat.json',JSON.stringify({status:'PASS',scope:'REAL_PG_MINIO_TEXT_INTAKE_SIGNED_GATEWAY_AUTHORIZATION_AND_TARGET_WIRE_ARCHIVE',upstreamModelCalled:false,mediaQualification:false,checks},null,2));
}
main().catch(error=>{writeFileSync(out+'/derived-chat.json',JSON.stringify({status:'FAIL',checks,error:error instanceof Error?error.message.slice(0,300):'FAILED'},null,2));console.error(error instanceof Error?error.message:'FAILED');process.exitCode=1;}).finally(closeDatabaseConnection);
