import { authenticatedApi } from './auth.mjs';
import { chromium, expect } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
const out = resolve(process.argv[2] ?? '');
const f = JSON.parse(readFileSync(out + '/fixture.private.json', 'utf8'));
if (f.dataset !== 'SYNTHETIC_ONLY_NEW_EMPTY_DATABASE' || f.baseURL !== 'http://127.0.0.1:58089') throw new Error('ISOLATED_FIXTURE_REQUIRED');
const selected=process.env.JOURNEY_IDS?.split(',')??Array.from({length:17},(_,index)=>'J'+String(index+1).padStart(2,'0'));
if(selected.includes('J18'))throw new Error('USE_AUTH_WORKFLOWS_WITH_DEDICATED_LOGOUT_SUBJECTS');
if(selected.includes('J17')&&!existsSync(out+'/crawl.json'))throw new Error('CRAWL_REQUIRED_BEFORE_MOBILE_JOURNEY');
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({baseURL:f.baseURL,viewport:{width:1440,height:1000}});
if(process.env.REUSE_SESSION==='1'){const session=await authenticatedApi(out);try{const state=await session.api.storageState();await context.addCookies(state.cookies);}finally{await session.api.dispose();}}
const page = await context.newPage(); page.setDefaultTimeout(7000);
const prefix = 'AUTO' + Date.now(); const results = [], requests = [], errors = [];
mkdirSync(out + '/screenshots', {recursive:true});
page.on('response',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/'))requests.push({path:u.pathname,method:r.request().method(),status:r.status()});});
page.on('pageerror',e=>errors.push(e.message.slice(0,350)));
const go = async path => {await page.goto(path);await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});};
const dialog=()=>page.getByRole('dialog');
async function mutate(path,method,action,expected=[200]) {
 const promise=page.waitForResponse(r=>(typeof path==='string'?new URL(r.url()).pathname===path:path.test(new URL(r.url()).pathname))&&r.request().method()===method,{timeout:10000});
 promise.catch(()=>{}); await action(); const response=await promise; const data=await response.json().catch(()=>({}));
 if(!expected.includes(response.status()))throw new Error('HTTP_'+response.status()+' '+path+' '+JSON.stringify(data).slice(0,350));
 return data;
}
async function step(id,module,action) {
 if(!selected.includes(id))return;
 const start=Date.now(), ri=requests.length, ei=errors.length; let status='PASS',detail;
 try {detail=await action(); if(errors.length>ei)throw new Error(errors.slice(ei).join(';')); if(detail?.diagnosticOnly)status='OBSERVATION';}
 catch(e){status='FAIL';detail={error:e.message.slice(0,600),ui:(await page.locator('body').innerText()).slice(-2200)};}
 // Never capture one-time credentials or password values.
 await page.screenshot({path:out+'/screenshots/'+id+'.png',fullPage:true,mask:[page.locator('input[type=password]'),page.locator('pre')]}).catch(()=>{});
 results.push({id,module,status,detail,milliseconds:Date.now()-start,requests:requests.slice(ri),pageErrors:errors.slice(ei)});
 writeFileSync(out+'/'+(process.env.JOURNEY_OUTPUT??'journeys')+'.json',JSON.stringify({scope:'REAL_BROWSER_REAL_BACKEND_SYNTHETIC_ONLY',prefix,results},null,2));
 console.log(JSON.stringify({id,module,status,detail:status==='FAIL'?detail.error:detail}));
 await page.keyboard.press('Escape').catch(()=>{});
}
try {
await step('J01','登录',async()=>{await go('/login');await page.getByPlaceholder('请输入用户名').fill(f.username);await page.getByPlaceholder('请输入密码').fill(f.password);await page.getByPlaceholder('请输入验证码').fill((await page.locator('.captcha').innerText()).trim());for(let attempt=0;attempt<2;attempt++){const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');await page.getByRole('button',{name:'登 录'}).click();const response=await pending;if(response.status()===200)break;if(response.status()!==429||attempt===1)throw new Error('LOGIN_'+response.status());const seconds=Number(response.headers()['retry-after']);if(!Number.isFinite(seconds)||seconds<1||seconds>901)throw new Error('LOGIN_RETRY_AFTER_INVALID');console.log('AUTH_RATE_LIMIT_WAIT_SECONDS '+seconds);await page.waitForTimeout((seconds+1)*1000);await page.getByPlaceholder('请输入验证码').fill((await page.locator('.captcha').innerText()).trim());}await page.waitForURL(u=>u.pathname==='/');await expect(page.getByRole('heading',{name:'安全对话工作台'})).toBeVisible();});
if(results.some(r=>r.id==='J01'&&r.status !== 'PASS')) throw new Error('AUTHENTICATION_PRECONDITION_FAILED');
await context.storageState({path:out+'/browser-state.private.json'});
await step('J02','策略创建与持久化',async()=>{await go('/policies');await page.getByRole('button',{name:'创建策略',exact:true}).click();await dialog().locator('#name').fill(prefix+'策略');await dialog().locator('#description').fill('自动化合成测试，可删除');await mutate('/api/policies','POST',()=>dialog().getByRole('button',{name:'创建',exact:true}).click());await page.reload();await expect(page.getByRole('button',{name:prefix+'策略',exact:true})).toBeVisible();});
await step('J03','策略详情与关键词检索',async()=>{await go('/policies/'+f.policyId);await page.getByRole('tab',{name:'关键词管理'}).click();await page.getByPlaceholder('搜索关键词...').fill('不存在的合成关键词');await expect(page.getByText('提示词注入 · 中英文覆盖目录',{exact:true})).toBeVisible();});
await step('J04','维度创建、编辑与规则详情',async()=>{await go('/dimensions');await page.getByRole('button',{name:'新建维度'}).click();await dialog().locator('#code').fill(prefix.toLowerCase());await dialog().locator('#name').fill(prefix+'维度');await mutate('/api/dimensions','POST',()=>dialog().getByRole('button',{name:'创建',exact:true}).click());await page.getByLabel('搜索维度').fill(prefix);await page.getByTitle('编辑',{exact:true}).click();await dialog().locator('#edit-name').fill(prefix+'维度改');await mutate(/^\/api\/dimensions\/[^/]+$/,'PUT',()=>dialog().getByRole('button',{name:'保存',exact:true}).click());await page.getByTitle('规则配置',{exact:true}).click();await expect(page.getByText(prefix+'维度改',{exact:true}).first()).toBeVisible();});
await step('J05','白名单完整表单与目标选择',async()=>{await go('/whitelist');await page.getByRole('button',{name:'新增白名单',exact:true}).click();await dialog().locator('#whitelist-name').fill(prefix+'白名单');await dialog().locator('#whitelist-pattern').fill('合成的受限例外');await dialog().getByRole('checkbox',{name:'自动化测试基线策略',exact:true}).check();await dialog().getByRole('checkbox',{name:/自动化标记-ad_detection/}).check();await mutate('/api/whitelist-rules','POST',()=>dialog().getByRole('button',{name:'保存待审批草稿'}).click());await page.reload();await expect(page.getByText(prefix+'白名单',{exact:false}).first()).toBeVisible();});
await step('J06','应用配置保存',async()=>{await go('/applications');await page.locator('#app-owner').fill('合成验收负责人');await mutate('/api/applications','PATCH',()=>page.getByRole('button',{name:'保存配置'}).click());await page.reload();await expect(page.locator('#app-owner')).toHaveValue('合成验收负责人');});
await step('J07','应用新建',async()=>{await go('/applications');await page.getByRole('button',{name:'新建应用',exact:true}).click();await dialog().locator('#create-code').fill(prefix.toLowerCase());await dialog().locator('#create-name').fill(prefix+'应用');await mutate('/api/applications','POST',()=>dialog().getByRole('button',{name:'创建应用',exact:true}).click(),[201]);await page.reload();await page.getByRole('combobox',{name:'选择应用',exact:true}).click();await expect(page.getByRole('option',{name:prefix+'应用',exact:true})).toBeVisible();await page.keyboard.press('Escape');});
await step('J08','应用凭据签发与撤销',async()=>{await go('/applications');await page.getByRole('button',{name:'签发凭据',exact:true}).click();await dialog().locator('#key-name').fill(prefix+'临时凭据');await mutate('/api/application-credentials','POST',()=>dialog().getByRole('button',{name:'签发凭据',exact:true}).click(),[201]);await expect(dialog().getByText('凭据已签发',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await mutate('/api/application-credentials','DELETE',()=>page.getByRole('button',{name:'撤销',exact:true}).last().click());await page.reload();await expect(page.getByText(prefix+'临时凭据',{exact:true})).toHaveCount(0);});
await step('J09','验证样本创建',async()=>{await go('/test-cases');await page.getByRole('button',{name:'新增用例',exact:true}).click();await dialog().locator('#title').fill(prefix+'正常样本');await dialog().locator('#inputText').fill('请介绍产品服务流程。');await mutate('/api/test-cases','POST',()=>dialog().getByRole('button',{name:/创建|保存/}).click());await page.reload();await expect(page.getByText(prefix+'正常样本',{exact:true})).toBeVisible();});
await step('J10','验证样本文件批量导入',async()=>{await go('/test-cases');await page.getByRole('button',{name:'批量导入文本样本'}).click();await page.getByLabel('选择样本文件').setInputFiles({name:'synthetic.jsonl',mimeType:'application/x-ndjson',buffer:Buffer.from(JSON.stringify({title:prefix+'导入样本',inputText:'请介绍服务时间。',outputText:'工作日提供服务。',expectedAction:'allow'}))});await page.getByRole('button',{name:'预览校验'}).click();await page.getByRole('button',{name:'确认导入'}).click();await expect(page.getByText(/已导入 1 条|已导入1条/)).toBeVisible();});
await step('J11','响应模板创建、预览复检',async()=>{await go('/response-templates');await page.getByRole('button',{name:'新建版本'}).click();await dialog().locator('#template-key').fill(prefix.toLowerCase());await dialog().locator('#risk-category').fill('sensitive_compliance');await dialog().locator('#template-text').fill('请求已接收，请使用合规方式咨询。');await mutate('/api/policy-governance/templates','POST',()=>dialog().getByRole('button',{name:'创建版本'}).click(),[201]);await page.getByRole('button',{name:'预览复检',exact:true}).first().click();await page.getByRole('button',{name:'渲染并复检'}).click();await expect(dialog().getByText(/复检通过|复检未通过/).first()).toBeVisible();});
await step('J12','词典草稿、校验和测试',async()=>{await go('/dictionaries');await page.getByRole('button',{name:'新建草稿'}).click();await dialog().locator('#dictionary-id').fill(prefix.toLowerCase());await dialog().locator('#dictionary-version').fill('1.0.0');await dialog().getByRole('button',{name:'创建签名草稿'}).click();await expect(dialog()).toBeHidden();await page.getByRole('button',{name:'校验',exact:true}).first().click();await expect(page.getByText(/校验通过|校验完成/).first()).toBeVisible();await page.getByRole('button',{name:'测试',exact:true}).first().click();});
await step('J13','事件创建与处置',async()=>{await go('/incidents');await page.getByRole('button',{name:'新建事件',exact:true}).click();await dialog().locator('#incident-title').fill(prefix+'测试事件');await dialog().locator('#incident-risk').fill('synthetic_workflow');for(const field of await dialog().locator('textarea').all())await field.fill('合成事件验收说明');await mutate('/api/incidents','POST',()=>dialog().getByRole('button',{name:'创建事件'}).click(),[201]);await page.getByRole('button',{name:'查看事件详情'}).first().click();await page.locator('main').getByRole('combobox').last().click();await page.getByRole('option').first().click();await page.locator('#transition-note').fill('已核查合成数据，执行验收处置。');await page.getByRole('button',{name:'提交处置'}).click();await expect(page.getByText('已核查合成数据，执行验收处置。',{exact:true}).first()).toBeVisible();});
await step('J14','异步评测提交与结果',async()=>{await go('/evaluation-runs');await page.getByRole('button',{name:'选择当前',exact:true}).click();const data=await mutate('/api/evaluation-runs','POST',()=>page.getByRole('button',{name:'提交异步评测'}).click(),[202]);const id=data.data.id;let state;for(let i=0;i<35;i++){const r=await page.request.get('/api/evaluation-runs/'+id);expect(r.status()).toBe(200);state=(await r.json()).data;if(['completed','failed','cancelled'].includes(state.status))break;await page.waitForTimeout(1000);}expect(state.status,JSON.stringify({status:state.status,error:state.error})).toBe('completed');return {status:state.status,completedCases:state.completedCases,totalCases:state.totalCases};});
await step('J15','个人资料查看与保存',async()=>{await go('/');await page.getByRole('button',{name:'用户菜单'}).click();await page.getByRole('menuitem',{name:'信息修改'}).click();await dialog().getByPlaceholder('请输入部门').fill('自动化测试组');await dialog().getByRole('button',{name:/保存/}).click();await expect(dialog()).toBeHidden();});
await step('J16','导出全部范围统计',async()=>{await go('/export');await page.locator('main').getByRole('combobox').first().click();await page.getByRole('option',{name:'全部记录'}).click();const r=await page.request.get('/api/export/stats?days=0');expect(r.status()).toBe(200);return {stats:(await r.json()).data,downloadEnabled:await page.getByRole('button',{name:'下载已批准的报告',exact:true}).isEnabled()};});
await step('J17','移动端全部生产模块导航',async()=>{await page.setViewportSize({width:390,height:844});const paths=JSON.parse(readFileSync(out+'/crawl.json','utf8')).results.map(x=>x.path).filter(x=>!['/simulate','/model-eval'].includes(x));const overflow=[];for(const path of paths){await go(path);await expect(page.locator('main')).toBeVisible();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))overflow.push(path);}expect(overflow).toEqual([]);return {pages:paths.length};});
await step('J18','注销并阻断旧会话',async()=>{await page.setViewportSize({width:1440,height:1000});await go('/');await page.getByRole('button',{name:'用户菜单'}).click();await mutate('/api/auth/logout','POST',()=>page.getByRole('menuitem',{name:'退出登录'}).click(),[200]);await page.waitForURL(/\/login$/);expect((await page.request.get('/api/auth/me')).status()).toBe(401);});
} finally {await browser.close();}
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
