import{readFileSync,writeFileSync}from'node:fs';import{randomUUID}from'node:crypto';import{authenticatedApi}from'./auth.mjs';
const out=process.argv[2],s=await authenticatedApi(out),uploads=JSON.parse(readFileSync(out+'/upload-matrix.json','utf8')).results,results=[];
async function submit(items,label){const started=Date.now();let response=await s.api.post('/api/media/intake',{headers:s.headers,data:{policyId:s.fixture.policyId,artifactIds:items.map(x=>x.artifactId),taskPurpose:'SYNTHETIC_ENGINEERING_FORMAT_CHECK',idempotencyKey:randomUUID()}});
 if(response.status()===429){const delay=Number(response.headers()['retry-after']);if(delay<1||delay>61)throw new Error('INVALID_RATE_LIMIT');await new Promise(resolve=>setTimeout(resolve,(delay+1)*1000));response=await s.api.post('/api/media/intake',{headers:s.headers,data:{policyId:s.fixture.policyId,artifactIds:items.map(x=>x.artifactId),idempotencyKey:randomUUID()}});}
 if(response.status()!==202)throw new Error('INTAKE_'+response.status());const id=(await response.json()).data.id;let job;
 for(let n=0;n<100;n++){const r=await s.api.get('/api/v1/guard/jobs/'+id);if(r.status()!==200)throw new Error('JOB_'+r.status());job=(await r.json()).data;if(['completed','failed','cancelled'].includes(job.status))break;await new Promise(resolve=>setTimeout(resolve,1000));}
 const value=job?.result;const complete=job?.status==='completed'&&value?.operationalOutcome==='COMPLETE';const safeIncomplete=job?.status==='completed'&&value&&['INCOMPLETE','REQUIRES_REVIEW'].includes(value.operationalOutcome)&&['BLOCK','REQUIRE_REVIEW','SAFE_RESPONSE'].includes(value.action)&&Array.isArray(value.analysisCoverage)&&value.analysisCoverage.length>0;
 const classification=complete?'PASS':safeIncomplete?'BLOCKED':'FAIL';const result={id:'MEDIA:'+label,files:items.map(x=>x.name),jobId:id,status:classification,jobStatus:job?.status,failure:job?.failureHistory?.at(-1),action:value?.action,outcome:value?.operationalOutcome,reasonCodes:value?.degradationReasons??value?.reasonCodes??[],coverage:value?.analysisCoverage??[],milliseconds:Date.now()-started,semanticQualification:false};results.push(result);writeFileSync(out+'/media-stages.json',JSON.stringify({scope:'REAL_DECODE_AND_JOB_PIPELINE; SEMANTIC_MODEL_QUALIFICATION_SEPARATE',results},null,2));console.log(JSON.stringify({id:result.id,status:result.status,jobStatus:result.jobStatus,action:result.action,outcome:result.outcome}));}
try{for(const item of uploads.filter(x=>x.expected==='accepted'))await submit([item],item.name);
 for(const names of [['sample.docx','sample.png'],['audio.wav','sample.srt'],['video.mp4','audio.wav'],['legacy-gb18030.txt','sample.png','audio.wav']]){const items=names.map(name=>uploads.find(x=>x.name===name));if(items.some(x=>!x))results.push({id:'MIXED:'+names.join('+'),status:'FAIL',reason:'FIXTURE_MISSING'});else await submit(items,names.join('+'));}
}finally{await s.api.dispose();writeFileSync(out+'/media-stages.json',JSON.stringify({scope:'REAL_DECODE_AND_JOB_PIPELINE; SEMANTIC_MODEL_QUALIFICATION_SEPARATE',results},null,2));}
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;else if(results.some(r=>r.status==='BLOCKED'))process.exitCode=2;
