import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { and, eq } from 'drizzle-orm';
import { db, closeDatabaseConnection } from '@/storage/database/shared/db';
import { artifacts, guardJobs, ragSources, ragChunks } from '@/storage/database/shared/schema';
import { storeVerifiedBytes } from '@/lib/artifacts/server-upload';
import { submitGuardJob, cancelGuardJob } from '@/lib/guard-jobs';
import { processNextIntakeJob } from '@/lib/media/intake-worker';
import { processNextRagIngestJob } from '@/lib/rag/ingest-worker';
import { submitMediaRagIngest } from '@/lib/rag/media-ingest';
import { validateMediaRagLineage } from '@/lib/rag/media-lineage';
import { assertRagRetrievalAccess } from '@/lib/rag/retrieval';
const out = resolve(process.env.COMPREHENSIVE_RUN_DIR!);
const fixture = JSON.parse(readFileSync(out + '/fixture.private.json', 'utf8')) as {tenantId:string;applicationId:string;userId:string;bundleId:string;other:{userId:string}};
const scope={tenantId:fixture.tenantId,applicationId:fixture.applicationId},ownerId=fixture.userId;
const checks:Array<{id:string;status:'PASS'}>=[];
const check=(id:string)=>{checks.push({id,status:'PASS'});console.log(id+' PASS');};
async function main(){
 const url=new URL(process.env.DATABASE_URL!);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'5438');assert.match(url.pathname,/^\/guardllm_integration_full_\d+$/);
 const parent=await storeVerifiedBytes({scope,ownerId,kind:'TEXT',fileName:'rag-original.txt',mediaType:'text/plain',bytes:Buffer.from('The public library opens at nine in the morning. Visitors may borrow books for two weeks.')});
 await assert.rejects(submitGuardJob({scope,ownerId,artifactId:parent.id,sourceArtifactIds:[parent.id],expectedIntakeSources:[{artifactId:parent.id,sha256:'0'.repeat(64),kind:'TEXT'}],bundleId:fixture.bundleId,jobType:'intake',idempotencyKey:randomUUID(),maxAttempts:1}),/expected manifest/);check('MANIFEST_WRONG_SOURCE_DIGEST_REJECTED');
 const submitted=await submitGuardJob({scope,ownerId,artifactId:parent.id,sourceArtifactIds:[parent.id],bundleId:fixture.bundleId,jobType:'intake',idempotencyKey:randomUUID(),maxAttempts:1});
 assert.deepEqual(await processNextIntakeJob(),{jobId:submitted.job.id,status:'completed'});
 const [intake]=await db.select().from(guardJobs).where(eq(guardJobs.id,submitted.job.id));
 assert.equal(intake.status,'completed');assert.equal(intake.result?.operationalOutcome,'COMPLETE');check('REAL_TEXT_INTAKE_CREATED_NORMALIZED_ASSET');
 const input={intakeJobId:intake.id,sourceUri:'urn:synthetic:library',idempotencyKey:randomUUID()};
 const imported=await submitMediaRagIngest(scope,ownerId,input);assert.equal(imported.jobs.length,1);assert.equal(imported.nativeCoverageClaimed,false);
 const repeated=await submitMediaRagIngest(scope,ownerId,input);assert.equal(repeated.jobs[0].jobId,imported.jobs[0].jobId);assert.equal(repeated.jobs[0].reused,true);check('MEDIA_RAG_SUBMISSION_IDEMPOTENT');
 await assert.rejects(submitMediaRagIngest(scope,fixture.other.userId,input),/UNAVAILABLE/);check('MEDIA_RAG_OWNER_ISOLATION');
 assert.equal((await processNextRagIngestJob())?.status,'completed');
 const [source]=await db.select().from(ragSources).where(eq(ragSources.artifactId,imported.jobs[0].artifactId));
 const [chunk]=await db.select().from(ragChunks).where(eq(ragChunks.artifactId,imported.jobs[0].artifactId));
 assert.ok(source);assert.ok(chunk);assert.equal(source.state,'accepted');assert.equal(source.sourceType,'NORMALIZED_MEDIA');
 assert.deepEqual(source.acl,{allowedPrincipals:[ownerId],allowedRoles:[]});assert.equal(source.trustLevel,0);check('REAL_NORMALIZED_RAG_INGEST_PERSISTED_OWNER_ACL');
 assert.throws(()=>assertRagRetrievalAccess({scope,source,principal:{id:fixture.other.userId,roles:['SYSTEM_ADMIN'],clearance:10}}),/ACCESS_DENIED/);check('RAG_FOREIGN_PRINCIPAL_CANNOT_READ_PROJECTION');
 const [ragArtifact]=await db.select().from(artifacts).where(eq(artifacts.id,imported.jobs[0].artifactId));
 assert.ok(ragArtifact.contentExpiresAt<=parent.contentExpiresAt);
 const lineage=ragArtifact.metadata!.mediaLineage;
 await validateMediaRagLineage(db,scope,ownerId,lineage);
 await db.update(artifacts).set({state:'quarantined'}).where(eq(artifacts.id,parent.id));
 await assert.rejects(validateMediaRagLineage(db,scope,ownerId,lineage),/UNAVAILABLE/);
 await db.update(artifacts).set({state:'accepted'}).where(eq(artifacts.id,parent.id));check('RAG_ORIGINAL_REVOCATION_RECHECKED');
 await db.update(guardJobs).set({result:{...intake.result,degraded:true}}).where(eq(guardJobs.id,intake.id));
 await assert.rejects(validateMediaRagLineage(db,scope,ownerId,lineage),/JOB_CHANGED/);
 await db.update(guardJobs).set({result:intake.result}).where(eq(guardJobs.id,intake.id));check('RAG_INTAKE_RESULT_DIGEST_CHANGE_REJECTED');
 const cancellation=await submitMediaRagIngest(scope,ownerId,{...input,idempotencyKey:randomUUID()});
 await cancelGuardJob(scope,ownerId,cancellation.jobs[0].jobId);assert.equal(await processNextRagIngestJob(),null);
 assert.equal((await db.select().from(ragSources).where(eq(ragSources.artifactId,cancellation.jobs[0].artifactId))).length,0);check('CANCELLED_MEDIA_RAG_CANNOT_INDEX');
 // Simulated missing-role state tests the gate only; no model qualification is manufactured.
 await db.update(guardJobs).set({result:{...intake.result,operationalOutcome:'INCOMPLETE',releaseEligibility:{eligible:false},degradationReasons:['NATIVE_ROLE_NOT_CONFIGURED']}}).where(eq(guardJobs.id,intake.id));
 await assert.rejects(submitMediaRagIngest(scope,ownerId,{...input,idempotencyKey:randomUUID()}),/INCOMPLETE/);
 await db.update(guardJobs).set({result:intake.result}).where(and(eq(guardJobs.id,intake.id),eq(guardJobs.ownerId,ownerId)));check('INCOMPLETE_MEDIA_COVERAGE_CANNOT_INDEX');
 writeFileSync(out+'/normalized-rag.json',JSON.stringify({status:'PASS',scope:'ISOLATED_REAL_POSTGRES_MINIO_AND_TEXT_WORKERS',nativeModelQualification:false,checks},null,2));
}
main().catch(error=>{writeFileSync(out+'/normalized-rag.json',JSON.stringify({status:'FAIL',checks,error:error instanceof Error?error.message.slice(0,300):'FAILED'},null,2));console.error(error instanceof Error?error.message:'FAILED');process.exitCode=1;}).finally(closeDatabaseConnection);
