import { z } from 'zod';
export const tracePaginationSchema = z.object({ nextCursor: z.string().nullable(), hasMore: z.boolean(), watermark: z.iso.datetime(), eventWatermark: z.number().int().nonnegative(), eventGaps: z.array(z.object({ from: z.number().int(), to: z.number().int() })), stepsHaveMore: z.boolean(), eventsHaveMore: z.boolean() }).strict();
const requestSchema = z.object({ id:z.string(), snapshotId:z.string(), subjectId:z.string(), sessionId:z.string().nullable(), state:z.string(), preparationState:z.string().optional(), stepCount:z.number(), lastEventSeq:z.number(), sessionFinalized:z.boolean(), createdAt:z.string(), expiresAt:z.string() });
export const gatewayRequestListSchema = z.object({ items:z.array(requestSchema), totals:z.array(z.object({state:z.string(),count:z.number()})), timeRange:z.enum(['24h', 'custom']),limit:z.number(),nextCursor:z.string().nullable().optional(),hasMore:z.boolean().optional(),from:z.iso.datetime().optional(),to:z.iso.datetime().optional() });
export const gatewayRequestDetailSchema = z.object({ pagination: tracePaginationSchema.optional(), resources: z.object({ state:z.string(), preparedInputChars:z.number().nullable(), inspectedChars:z.number(), inspectionSteps:z.number(), preparedReferences:z.number().nullable(), admissionHmac:z.string(), settlementHmac:z.string().nullable(), settledAt:z.string().nullable(), modelOutcome:z.string().nullable() }).nullable().optional(), request:requestSchema.nullable(), steps:z.array(z.object({id:z.string(),stage:z.string(),streamSeq:z.number(),attemptKind:z.string(),decisionId:z.string().nullable(),action:z.string().nullable(),coverage:z.string(),status:z.string(),latencyMs:z.number().nullable(),modelVersions:z.array(z.string()),createdAt:z.string()})),
  events:z.array(z.object({sequence:z.number(),auditBatchId:z.string().uuid().nullable().optional(),kind:z.string(),stepId:z.string().nullable(),decisionId:z.string().nullable(),recheckDecisionId:z.string().nullable(),actualAction:z.string().nullable(),reasonCode:z.string().nullable(),rangeStart:z.number().nullable(),rangeEnd:z.number().nullable(),payloadHmac:z.string().nullable(),createdAt:z.string()})),writeAcceptedMeaning:z.string() });
export type GatewayRequestList = z.infer<typeof gatewayRequestListSchema>;
export type GatewayRequestDetail = z.infer<typeof gatewayRequestDetailSchema>;

export const gatewayConsoleQuerySchema = z.object({ cursor: z.string().max(4096).optional(), from: z.iso.datetime().optional(), to: z.iso.datetime().optional(), id: z.string().regex(/^[a-zA-Z0-9_-]{1,128}$/).optional(), state: z.enum(['AUTHORIZED','SEND_INTENT','UPSTREAM_STARTED','RELEASING','WRITTEN','COMPLETED','TERMINATED','REVIEW_REQUIRED','UPSTREAM_OUTCOME_UNKNOWN']).optional(), limit: z.coerce.number().int().min(1).max(100).default(50) }).strict();
export type GatewayConsoleQuery = z.infer<typeof gatewayConsoleQuerySchema>;
