import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID,randomBytes} from 'node:crypto';
import bcrypt from 'bcrypt';
import pg from 'pg';
import {chromium,expect,type Page} from '@playwright/test';
async function main(){
 const dir='.artifact-build/upgrade-implementation-20260907/environment',out='.artifact-build/v11-all-20260908';Object.assign(process.env,JSON.parse(readFileSync(dir+'/environment.json','utf8')));
 const url=new URL(process.env.PGDATABASE_URL!);if(url.hostname!=='127.0.0.1'||url.port!=='55447'||url.pathname!=='/guardllm_integration_gateway_v2')throw new Error('ISOLATED_DATABASE_REQUIRED');
 const {tenantId,applicationId}=JSON.parse(readFileSync(dir+'/fixture.json','utf8')) as {tenantId:string;applicationId:string};
 const {requestId}=JSON.parse(readFileSync(out+'/native-blocked-request.json','utf8')) as {requestId:string};
 const client=new pg.Client({connectionString:url.toString(),ssl:false});await client.connect();
 const [{projectSecurityAlerts},{closeDatabaseConnection}]=await Promise.all([import('../../src/lib/security-alerts/service'),import('../../src/storage/database/shared/db')]);
 for(let i=0;i<20;i++){if(!(await projectSecurityAlerts(100)).processed)break;}await closeDatabaseConnection();
 const users=Array.from({length:2},()=>({id:randomUUID(),username:'v11_'+randomUUID().slice(0,8),password:'T!9'+randomBytes(18).toString('base64')}));
 for(const user of users){await client.query("insert into users(id,username,nickname,password,role,status,must_change_password,password_changed_at) values($1,$2,'Synthetic V1.1 browser reviewer',$3,'SYSTEM_ADMIN','active',false,now())",[user.id,user.username,await bcrypt.hash(user.password,12)]);await client.query("insert into tenant_memberships(tenant_id,user_id,default_application_id,status) values($1,$2,$3,'active')",[tenantId,user.id,applicationId]);}
 const [candidateAlert]=(await client.query('select id from security_alerts where tenant_id=$1 and application_id=$2 and request_id=$3 order by occurred_at desc limit 1',[tenantId,applicationId,requestId])).rows as {id:string}[];assert.ok(candidateAlert);
 const [candidateSource]=(await client.query("select id from archived_content_objects where tenant_id=$1 and application_id=$2 and request_id=$3 and purpose='RECEIVED_INPUT' and sequence=2",[tenantId,applicationId,requestId])).rows as {id:string}[];assert.ok(candidateSource);
 const base='https://localhost:5107',browser=await chromium.launch({headless:true,channel:'chrome'}),errors:string[]=[],checks:string[]=[];
 async function pageFor(user:typeof users[number]){const context=await browser.newContext({baseURL:base,ignoreHTTPSErrors:true,clientCertificates:[{origin:base,certPath:dir+'/tls/client.crt',keyPath:dir+'/tls/client.key'}],viewport:{width:1440,height:1050}});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&/hydration|did not match|invalid html/i.test(message.text()))errors.push(message.text());});await page.goto('/login');await page.getByPlaceholder('请输入用户名').fill(user.username);await page.getByPlaceholder('请输入密码').fill(user.password);await page.getByPlaceholder('请输入验证码').fill((await page.locator('.captcha').innerText()).trim());await page.getByRole('button',{name:'登 录'}).click();await expect(page).not.toHaveURL(/\/login(?:[?]|$)/,{timeout:30000});return page;}
 async function openPrepared(page:Page,sequence=2,targetRequest=requestId){await page.goto('/conversations?request='+targetRequest);await expect(page.getByLabel('筛选请求 ID')).toHaveValue(targetRequest);await page.getByRole('button',{name:targetRequest,exact:true}).click();await page.getByText('接收输入 · 序号 '+sequence,{exact:true}).locator('..').locator('..').getByRole('button',{name:'原文访问'}).click();await expect(page.getByRole('heading',{name:'原文访问控制'})).toBeVisible();}
 async function feedbackPage(page:Page,selectSource=false){await page.goto('/security-alerts');await page.getByTestId('alert-row-'+candidateAlert.id).getByRole('button').click();await page.getByRole('tab',{name:'处置与反馈'}).click();if(selectSource){await page.getByLabel('评测候选归档来源').click();await page.getByRole('option').filter({hasText:candidateSource.id.slice(0,8)}).click();await expect(page.getByRole('heading',{name:'原文访问控制'})).toBeVisible();}}
 try{
  const first=await pageFor(users[0]);checks.push('browser_login');
  await first.goto('/security-alerts');await expect(first.getByRole('heading',{name:'安全告警明细'})).toBeVisible({timeout:30000});await first.locator('tbody tr button').first().click();for(const name of ['命中证据','判定过程','执行链路','对话上下文','处置与反馈'])await expect(first.getByRole('tab',{name,exact:true})).toBeVisible();await first.getByRole('tab',{name:'处置与反馈'}).click();await expect(first.getByRole('heading',{name:'检测纠错反馈'})).toBeVisible();await first.screenshot({path:out+'/security-alerts.png',fullPage:true});checks.push('alert_five_tabs_and_feedback');
  await openPrepared(first);await first.getByRole('button',{name:'申请查看',exact:true}).click();await first.getByLabel('必要性说明（不得粘贴原文）').fill('Synthetic browser validation of original evidence access only.');await first.getByRole('button',{name:'提交申请',exact:true}).click();await expect(first.getByText('pending',{exact:true})).toBeVisible();checks.push('original_access_request');
  const second=await pageFor(users[1]);await openPrepared(second);await second.getByRole('button',{name:'审核',exact:true}).click();await second.getByLabel('审批意见（不得粘贴原文）').fill('Independent synthetic browser review for the exact archived content.');await second.getByRole('button',{name:'批准一次查看',exact:true}).click();await expect(second.getByRole('dialog',{name:'审核原文访问'})).not.toBeVisible();checks.push('independent_access_approval');
  await openPrepared(first);await first.clock.install();await first.getByRole('button',{name:'一次性查看',exact:true}).click();await expect(first.getByRole('dialog',{name:'临时原文证据'})).toBeVisible();await expect(first.locator('mark').filter({hasText:'SYNTHETIC_BLOCK_MARKER'})).toBeVisible();await first.screenshot({path:out+'/authorized-highlight.png',fullPage:true});checks.push('authorized_exact_version_highlight');
  await first.clock.fastForward(61000);await expect(first.getByRole('dialog',{name:'临时原文证据'})).not.toBeVisible();await expect(first.locator('mark')).toHaveCount(0);checks.push('temporary_original_cleared');
  await openPrepared(first,1);await first.getByRole('button',{name:'申请查看',exact:true}).click();await first.getByLabel('必要性说明（不得粘贴原文）').fill('Synthetic browser validation of original image preview only.');await first.getByRole('button',{name:'提交申请',exact:true}).click();await expect(first.getByText('pending',{exact:true})).toBeVisible();
  await openPrepared(second,1);await second.getByRole('button',{name:'审核',exact:true}).click();await second.getByLabel('审批意见（不得粘贴原文）').fill('Independent synthetic approval of the original image bytes.');await second.getByRole('button',{name:'批准一次查看',exact:true}).click();await expect(second.getByRole('dialog',{name:'审核原文访问'})).not.toBeVisible();
  await openPrepared(first,1);await first.getByRole('button',{name:'一次性查看',exact:true}).click();await expect(first.getByRole('img',{name:'授权查看的原始图片'})).toBeVisible();await expect(first.getByLabel('已验证命中区域')).toBeVisible();await expect(first.getByLabel('已验证命中区域').locator('rect')).toHaveCount(1);await first.getByRole('button',{name:'关闭并清除'}).click();await expect(first.getByRole('img',{name:'授权查看的原始图片'})).toHaveCount(0);checks.push('authorized_original_media_preview_and_clear');
  for(const kind of ['audio','video']){const fixture=JSON.parse(readFileSync(out+'/native-'+kind+'-request.json','utf8')) as {requestId:string};
   await openPrepared(first,1,fixture.requestId);await first.getByRole('button',{name:'申请查看',exact:true}).click();await first.getByLabel('必要性说明（不得粘贴原文）').fill('Synthetic codec and source-time browser validation only.');await first.getByRole('button',{name:'提交申请',exact:true}).click();await expect(first.getByText('pending',{exact:true})).toBeVisible();
   await openPrepared(second,1,fixture.requestId);await second.getByRole('button',{name:'审核',exact:true}).click();await second.getByLabel('审批意见（不得粘贴原文）').fill('Independent approval of synthetic media preview.');await second.getByRole('button',{name:'批准一次查看',exact:true}).click();await expect(second.getByRole('dialog',{name:'审核原文访问'})).not.toBeVisible();
   await openPrepared(first,1,fixture.requestId);await first.getByRole('button',{name:'一次性查看',exact:true}).click();const media=first.locator(kind);await expect(media).toBeVisible();await expect.poll(()=>media.evaluate(element=>(element as HTMLMediaElement).readyState)).toBeGreaterThan(0);await first.getByRole('button',{name:/跳转 0.10/}).click();await expect.poll(()=>media.evaluate(element=>(element as HTMLMediaElement).currentTime)).toBeGreaterThanOrEqual(0.09);await first.getByRole('button',{name:'关闭并清除'}).click();await expect(media).toHaveCount(0);checks.push('authorized_'+kind+'_decode_seek_and_clear');
  }
  await feedbackPage(first);await first.getByLabel('纠错依据').fill('Synthetic browser candidate preparation validation only.');await first.getByRole('button',{name:'提交复核',exact:true}).click();await expect(first.getByText('已进入待复核队列，尚未修改检测策略。')).toBeVisible();
  await feedbackPage(second);await second.getByRole('button',{name:'复核此反馈',exact:true}).click();await second.getByLabel('复核意见',{exact:true}).fill('Independent synthetic feedback validation, not a policy publication.');await second.getByRole('button',{name:'确认反馈',exact:true}).click();await expect(second.getByRole('heading',{name:'反馈转评测候选'})).toBeVisible();checks.push('independent_feedback_triage');
  await feedbackPage(first,true);await first.getByRole('button',{name:'申请查看',exact:true}).click();await first.getByLabel('必要性说明（不得粘贴原文）').fill('Synthetic browser candidate export with an approved internal source.');await first.getByRole('button',{name:'提交申请',exact:true}).click();await expect(first.getByText('pending',{exact:true})).toBeVisible();
  await feedbackPage(second,true);await second.getByRole('button',{name:'审核',exact:true}).click();await second.getByLabel('审批意见（不得粘贴原文）').fill('Approve synthetic source for internal candidate preparation.');await second.getByRole('button',{name:'批准一次查看',exact:true}).click();await expect(second.getByRole('dialog',{name:'审核原文访问'})).not.toBeVisible();
  await feedbackPage(first,true);await first.getByRole('button',{name:'生成评测候选包',exact:true}).click();await first.getByLabel('内部使用授权依据').fill('SYNTHETIC_BROWSER_FIXTURE');await first.getByLabel('样本性质',{exact:true}).click();await first.getByRole('option',{name:'工程或合成样本'}).click();
  const downloaded=first.waitForEvent('download');await first.getByRole('button',{name:'消费授权并下载候选',exact:true}).click();const download=await downloaded;await download.saveAs(out+'/browser-feedback-candidate.json');const candidate=JSON.parse(readFileSync(out+'/browser-feedback-candidate.json','utf8')) as {qualityStatus:string;records:{case:{annotationStatus:string;authorizedExternalUse:boolean};reviews:unknown[]}[]};assert.equal(candidate.qualityStatus,'INSUFFICIENT_EVIDENCE');assert.equal(candidate.records[0].case.annotationStatus,'needs_review');assert.equal(candidate.records[0].case.authorizedExternalUse,false);assert.deepEqual(candidate.records[0].reviews,[]);await expect(first.getByRole('button',{name:'生成评测候选包',exact:true})).not.toBeVisible();checks.push('one_time_approved_candidate_download');
  await first.goto('/gateway-requests?request='+requestId);await expect(first.locator('body')).toContainText(requestId);checks.push('gateway_trace_deep_link');assert.deepEqual(errors,[]);checks.push('no_hydration_or_page_errors');
 }finally{await browser.close();for(const user of users)await client.query("update users set status='disabled' where id=$1",[user.id]);await client.end();writeFileSync(out+'/p6-ui.json',JSON.stringify({status:checks.length===13&&!errors.length?'PASS':'FAIL',checks,errors,syntheticDataOnly:true,browser:'installed-chrome',syntheticCoordinateFixture:true},null,2));}
 console.log('PASS browser checks: '+checks.join(', '));
}
main().catch(error=>{console.error(error instanceof Error?error.message:'UI_CHECK_FAILED');process.exitCode=1;});
