import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import https from 'node:https';
import {and,eq} from 'drizzle-orm';
async function main(){
 const directory='.artifact-build/upgrade-implementation-20260907/environment';Object.assign(process.env,JSON.parse(readFileSync(directory+'/environment.json','utf8')));
 const url=new URL(process.env.PGDATABASE_URL!);if(url.hostname!=='127.0.0.1'||url.port!=='55447'||url.pathname!=='/guardllm_integration_gateway_v2')throw new Error('ISOLATED_DATABASE_REQUIRED');
 const fixture=JSON.parse(readFileSync(directory+'/fixture.json','utf8')) as {tenantId:string;applicationId:string;apiKey:string};
 const native=JSON.parse(readFileSync('.artifact-build/v11-all-20260908/native-proxy-fixture.json','utf8')) as {bundleId:string;bundleDigest:string};
 const {principalId}=JSON.parse(readFileSync(directory+'/rag-model-fixture.json','utf8')) as {principalId:string};
 const tls={ca:readFileSync(directory+'/tls/ca.crt'),cert:readFileSync(directory+'/tls/client.crt'),key:readFileSync(directory+'/tls/client.key')};
 const [{db,closeDatabaseConnection},s,{canonicalJson,sha256},{nativeBindingDigest},{readArchivedContent}]=await Promise.all([import('../../src/storage/database/shared/db'),import('../../src/storage/database/shared/schema'),import('../../src/lib/gateway-runtime/protocol'),import('../../src/lib/multimodal/native-gate'),import('../../src/lib/conversation-archive/service')]);
 const scope={tenantId:fixture.tenantId,applicationId:fixture.applicationId},results:{id:string;status:string}[]=[];
 const fixtureDirectory='.artifact-build/v11-continuation-20260908/codec-fixtures';
 const mediaBytes={IMAGE:readFileSync(fixtureDirectory+'/image.png'),AUDIO:readFileSync(fixtureDirectory+'/audio.wav'),VIDEO:readFileSync(fixtureDirectory+'/video.mp4')};const bytes=mediaBytes.IMAGE;
 const [template]=await db.select().from(s.artifacts).where(and(eq(s.artifacts.tenantId,scope.tenantId),eq(s.artifacts.applicationId,scope.applicationId),eq(s.artifacts.state,'accepted'))).limit(1);assert.ok(template);
 async function put(id:string,raw:Uint8Array){const response=await fetch('http://127.0.0.1:58089/test/native-object',{method:'POST',body:JSON.stringify({id,base64:Buffer.from(raw).toString('base64')})});assert.equal(response.status,200);}
 async function artifact(kind:'TEXT'|'IMAGE'|'AUDIO'|'VIDEO',raw:Uint8Array){const id=randomUUID(),digest=createHash('sha256').update(raw).digest('hex');await put(id,raw);await db.insert(s.artifacts).values({...template,...scope,id,ownerId:principalId,kind,fileName:'synthetic-native-'+id,declaredMediaType:({TEXT:'text/plain',IMAGE:'image/png',AUDIO:'audio/wav',VIDEO:'video/mp4'}[kind]),detectedMediaType:({TEXT:'text/plain',IMAGE:'image/png',AUDIO:'audio/wav',VIDEO:'video/mp4'}[kind]),declaredSize:raw.length,verifiedSize:raw.length,declaredSha256:digest,verifiedSha256:digest,objectPrefix:'native-fixtures/'+id,partCount:1,partSize:5242880,state:'accepted',idempotencyKey:id,requestHash:digest,createdAt:new Date(),contentExpiresAt:new Date(Date.now()+3600000)});await db.insert(s.artifactParts).values({...scope,artifactId:id,partNumber:1,sizeBytes:raw.length,sha256:digest,objectKey:'native-fixtures/'+id,state:'verified',verifiedAt:new Date()});return{id,digest};}
 async function sample(text='NATIVE_NORMAL',modalities:('IMAGE'|'AUDIO'|'VIDEO')[]=['IMAGE'],archiveEvidence=true){
  const id=randomUUID(),body={model:'test',stream:false,messages:[{role:'user',content:text+' '+id}]},context=await artifact('TEXT',Buffer.from(canonicalJson(body))),jobId=randomUUID();
  const media=await Promise.all(modalities.map(async kind=>({kind,...await artifact(kind,mediaBytes[kind]),sizeBytes:mediaBytes[kind].length,mimeType:{IMAGE:'image/png',AUDIO:'audio/wav',VIDEO:'video/mp4'}[kind]}))),image=media[0];
  const binding={version:'1.0' as const,...scope,bundleDigest:native.bundleDigest,direction:'INPUT' as const,contextDigest:context.digest,requiredRiskIds:['prompt_injection'],sources:[{sourceId:'context:'+context.id,artifactId:context.id,sha256:context.digest,contentVersion:context.digest,modality:'TEXT' as const},...media.map(item=>({sourceId:'artifact:'+item.id,artifactId:item.id,sha256:item.digest,contentVersion:item.digest,modality:item.kind}))]};
  const assessment={version:'1.0',bindingDigest:nativeBindingDigest(binding),modelId:'synthetic-native',modelDigest:'e'.repeat(64),analyzerVersion:'synthetic-native-1',verdict:'NOT_DETECTED',riskIds:[],analyzedSourceIds:binding.sources.map(source=>source.sourceId),coverageScope:'GLOBAL',processingComplete:true,relations:[],reasonCodes:[]};
  await db.insert(s.guardJobs).values({...scope,id:jobId,ownerId:principalId,artifactId:image.id,contextArtifactId:context.id,bundleId:native.bundleId,jobType:'native_joint',status:'completed',idempotencyKey:jobId,requestHash:sha256(jobId),completedAt:new Date(),executionBinding:{version:'native-job-1',direction:'INPUT',contextArtifactId:context.id,contextSha256:context.digest,artifacts:media.map(item=>({id:item.id,sha256:item.digest,kind:item.kind,mediaType:item.mimeType,sizeBytes:item.sizeBytes}))},result:{action:'ALLOW',nativeBinding:binding,nativeAssessment:assessment,releaseEligibility:{eligible:true}}});
  if(archiveEvidence){const {enqueueMediaEvidenceSnapshot,publishMediaEvidence}=await import('../../src/lib/evidence/media-snapshots');
  const {makeEvidenceView}=await import('../../src/lib/evidence/media-views');
  const [savedJob]=await db.select().from(s.guardJobs).where(eq(s.guardJobs.id,jobId));
  const fixtureViews=media.map(item=>makeEvidenceView({artifactId:item.id,sourceDigest:item.digest,text:'SYNTHETIC_DERIVED_MARKER',source:'synthetic_engineering_fixture',contentPath:'/views/original',viewId:item.kind==='VIDEO'?'frame_1':'original',...(item.kind==='IMAGE'?{region:[0.1,0.2,0.5,0.6] as const}:item.kind==='AUDIO'?{startMs:100,endMs:200}:{startMs:100,endMs:100,frameIndex:1})}));
  const mappings=media.map(item=>({artifactId:item.id,viewId:item.kind==='VIDEO'?'frame_1':'original',...(item.kind==='IMAGE'?{basis:'DISPLAY_ORIENTED_SOURCE_PAGE',mappingVersion:'inverse-image-view-1',sourceWidth:101,sourceHeight:99,matrix:[1,0,0,0,1,0]}:item.kind==='AUDIO'?{basis:'SOURCE_TIME_MS',mappingVersion:'audio-time-to-source-1',sourceDurationMs:300,timeScale:1}:{basis:'SOURCE_TIME_MS',mappingVersion:'video-frame-to-source-1',frameIndex:1,timeMs:100})}));
  const {enqueueDecisionRecord}=await import('../../src/lib/security-alerts/service');
  const snapshot=await db.transaction(async tx=>{const stored=await enqueueMediaEvidenceSnapshot(tx,savedJob,{views:[makeEvidenceView({artifactId:context.id,sourceDigest:context.digest,text:canonicalJson(body),source:'user_text',contentPath:'/views/original'}),...fixtureViews],mappings});
   await enqueueDecisionRecord(tx,scope,{version:'1.0',source:'GUARD_JOB',sourceId:jobId,jobId,traceId:'synthetic-'+jobId,decisionId:sha256(jobId),stage:'INPUT',action:'WARN',occurredAt:new Date().toISOString(),coverage:{syntheticCoordinateFixture:true,realModelQuality:false},findings:[{riskId:'test.synthetic.media_coordinates',category:'UNDETERMINED',score:0,reasonCode:'SYNTHETIC_COORDINATE_FIXTURE',evidence:fixtureViews.map(({text,source:_source,...location},index)=>({evidenceId:'synthetic-'+index,locationState:'VERIFIED',locations:[{...location,textStart:0,textEnd:text.length,textLength:text.length}]}))}]});return stored;});

  await publishMediaEvidence(scope,snapshot.id);}
  return{id,body,image,jobId,reference:{artifactId:image.id,sha256:image.digest,jobId},references:media.map(item=>({artifactId:item.id,sha256:item.digest,jobId}))};
 }
 async function send(input:Awaited<ReturnType<typeof sample>>,change?:Record<string,unknown>){return new Promise<{status:number;body:string}>((resolve,reject)=>{const req=https.request('https://127.0.0.1:58087/v1/chat/completions',{...tls,method:'POST',signal:AbortSignal.timeout(65000),headers:{'content-type':'application/json',authorization:'Bearer '+fixture.apiKey,'x-request-id':input.id,'idempotency-key':input.id,'x-guard-deadline':String(Date.now()+45000)}},response=>{const chunks:Buffer[]=[];response.on('data',(chunk:Buffer)=>chunks.push(chunk));response.on('end',()=>resolve({status:response.statusCode??0,body:Buffer.concat(chunks).toString('utf8')}));response.on('error',reject);});req.on('error',reject);req.end(JSON.stringify({...input.body,guard_artifacts:input.references,...change}));});}
 async function calls(){return new Promise<Record<string,unknown>[]>((resolve,reject)=>{https.get('https://127.0.0.1:58088/test/calls',{...tls,signal:AbortSignal.timeout(5000)},response=>{const chunks:Buffer[]=[];response.on('data',(chunk:Buffer)=>chunks.push(chunk));response.on('end',()=>resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>[]));}).on('error',reject);});}
 async function test(id:string,run:()=>Promise<void>){await run();results.push({id,status:'PASS'});console.log('PASS '+id);}
 try{
  await test('NATIVE-PROXY-01 original bytes reach model with current job proof and archive',async()=>{const input=await sample(),before=(await calls()).length,response=await send(input);assert.equal(response.status,200,response.body);const sent=await calls();assert.equal(sent.length,before+1);const actual=sent.at(-1)!;const serialized=JSON.stringify(actual);assert.ok(serialized.includes('data:image/png;base64,'+bytes.toString('base64')));
   const objects=await db.select().from(s.archivedContentObjects).where(eq(s.archivedContentObjects.requestId,input.id));assert.equal(objects.length,7);
   const media=objects.find(item=>item.representation==='MEDIA_BYTES')!,model=objects.find(item=>item.purpose==='MODEL_INPUT')!;assert.ok(media&&model);const original=await readArchivedContent(scope,media.id),transmitted=await readArchivedContent(scope,model.id);
   assert.equal((original.content as {dataBase64:string}).dataBase64,bytes.toString('base64'));assert.deepEqual(transmitted.content,actual);
   let [archive]=await db.select().from(s.conversationArchives).where(eq(s.conversationArchives.requestId,input.id));
   for(let attempt=0;attempt<50&&archive.state==='OPEN';attempt++){await new Promise(resolve=>setTimeout(resolve,100));[archive]=await db.select().from(s.conversationArchives).where(eq(s.conversationArchives.requestId,input.id));}
   assert.equal(archive.state,'COMMITTED',JSON.stringify(archive.integrity));assert.equal(archive.mediaComplete,true);
   writeFileSync('.artifact-build/v11-all-20260908/native-success-request.json',JSON.stringify({requestId:input.id}));
  });
  for(const modalities of [['AUDIO'],['VIDEO'],['IMAGE','AUDIO','VIDEO']] as ('IMAGE'|'AUDIO'|'VIDEO')[][])await test('NATIVE-TRANSPORT-'+modalities.join('-')+' preserves typed bytes and source order',async()=>{const input=await sample('NATIVE_TYPED_TRANSPORT',modalities),before=(await calls()).length,response=await send(input);assert.equal(response.status,200,response.body);writeFileSync('.artifact-build/v11-all-20260908/native-'+modalities.join('-').toLowerCase()+'-request.json',JSON.stringify({requestId:input.id}));const sent=await calls();assert.equal(sent.length,before+1);const body=sent.at(-1) as {messages:{content:unknown}[]};const content=body.messages[0].content as {type:string;input_audio?:{data:string};image_url?:{url:string};video_url?:{url:string}}[];assert.deepEqual(content.slice(1).map(block=>block.type),modalities.map(kind=>({IMAGE:'image_url',AUDIO:'input_audio',VIDEO:'video_url'}[kind])));for(const [index,block] of content.slice(1).entries()){const encoded=block.input_audio?.data??(block.image_url?.url??block.video_url?.url??'').split(',')[1];assert.equal(encoded,mediaBytes[modalities[index]].toString('base64'));}});
  await test('NATIVE-PROXY-06 missing durable derived evidence never sends',async()=>{const input=await sample('NATIVE_MISSING_EVIDENCE',['IMAGE'],false),before=(await calls()).length,response=await send(input);assert.ok(response.status>=400);assert.equal((await calls()).length,before);});
  await test('NATIVE-PROXY-02 context changes require a new joint inspection',async()=>{const input=await sample(),before=(await calls()).length,response=await send(input,{messages:[{role:'user',content:'changed context'}]});assert.ok(response.status>=400);assert.equal((await calls()).length,before);});
  await test('NATIVE-PROXY-03 changed object bytes never reach the model',async()=>{const input=await sample(),before=(await calls()).length;await put(input.image.id,Buffer.from('tampered'));const response=await send(input);assert.ok(response.status>=400);assert.equal((await calls()).length,before);});
  await test('NATIVE-PROXY-04 clean native verdict preserves mandatory text denial',async()=>{const input=await sample('SYNTHETIC_BLOCK_MARKER'),before=(await calls()).length,response=await send(input);assert.equal(response.status,403,response.body);assert.equal((await calls()).length,before);writeFileSync('.artifact-build/v11-all-20260908/native-blocked-request.json',JSON.stringify({requestId:input.id}));});
  await test('NATIVE-PROXY-05 direct unsigned inline media is refused',async()=>{const input=await sample(),before=(await calls()).length,response=await send(input,{guard_artifacts:undefined,messages:[{role:'user',content:[{type:'image_url',image_url:{url:'data:image/png;base64,'+bytes.toString('base64')}}]}]});assert.ok(response.status>=400);assert.equal((await calls()).length,before);});
 }finally{await closeDatabaseConnection();writeFileSync('.artifact-build/v11-all-20260908/p4-native-proxy.json',JSON.stringify({status:results.length===9?'PASS':'FAIL',realModelQuality:false,syntheticQualification:true,syntheticCompletedAnalysisJobs:true,codecFixturesVerified:true,realOcrAsrOrJudgeQuality:false,results},null,2));}
}
main().catch(error=>{console.error(error instanceof Error?error.message:'NATIVE_PROXY_FAILED');process.exitCode=1;});
