import { readFileSync, readdirSync } from 'node:fs';
import { spawn } from 'node:child_process';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../..');
const directory = path.join(root, '.artifact-build/upgrade-implementation-20260907/environment');
const jar = path.join(root, 'services/guard-gateway/target/guard-gateway-1.0.0-SNAPSHOT.jar');
const mode = process.argv[2];
const xml=readFileSync(path.join(root,'services/guard-gateway/target/surefire-reports/TEST-com.guardllm.gateway.GatewayV2ContentTest.xml'),'utf8');
const classpath=xml.match(/name="java.class.path" value="([^"]+)"/)[1].replaceAll('&amp;','&').split(':').filter(item=>item&&!item.includes('/test-classes')).join(':');
const classMounts=['-v',`${path.join(root,'services/guard-gateway/target/classes')}:/workspace/services/guard-gateway/target/classes`,'-v',`${path.join(process.env.USERPROFILE,'.m2/repository')}:/root/.m2/repository:ro`];
let args;
if (mode === 'build') args = ['run','--rm','--pull=never','--network','none','-v',`${root}:/workspace`,'-v',`${path.join(process.env.USERPROFILE, '.m2/repository')}:/root/.m2/repository:ro`,'-w','/workspace/services/guard-gateway','maven:3.9.12-eclipse-temurin-21','mvn','-o','-B','-DskipTests','package'];
else if (mode === 'compile-fast') args=['run','--rm','--pull=never','--network','none',...classMounts,'-v',`${path.join(root,'services/guard-gateway/src/main/java')}:/sources:ro`,'maven:3.9.12-eclipse-temurin-21','javac','-parameters','-cp',classpath,'-d','/workspace/services/guard-gateway/target/classes',...readdirSync(path.join(root,'services/guard-gateway/src/main/java/com/guardllm/gateway')).filter(name=>name.endsWith('.java')).map(name=>'/sources/com/guardllm/gateway/'+name)];
else if (mode === 'start-classes') args=['run','--rm','--pull=never','--name','guardllm-upgrade-v2-java-20260907','--label','guardllm.scope=upgrade-v2-integration','-p','127.0.0.1:58087:58087','--env-file',path.join(directory,'gateway.env'),...classMounts,'-v',`${path.join(directory,'tls')}:/workspace/.artifact-build/upgrade-implementation-20260907/environment/tls:ro`,'maven:3.9.12-eclipse-temurin-21','java','-cp',classpath,'com.guardllm.gateway.GuardGatewayApplication'];
else if (mode === 'start') args = ['run','--rm','--pull=never','--name','guardllm-upgrade-v2-java-20260907','--label','guardllm.scope=upgrade-v2-integration','-p','127.0.0.1:58087:58087','--env-file',path.join(directory,'gateway.env'),'-v',`${jar}:/app/guard-gateway.jar:ro`,'-v',`${path.join(directory,'tls')}:/workspace/.artifact-build/upgrade-implementation-20260907/environment/tls:ro`,'maven:3.9.12-eclipse-temurin-21','java','-jar','/app/guard-gateway.jar'];
else throw new Error('Use gateway-v2-java.mjs build|start');
const child = spawn('docker', args, { stdio:'inherit', windowsHide:true });
for (const signal of ['SIGINT','SIGTERM']) process.once(signal, () => child.kill(signal));
child.on('exit', code => { process.exitCode=code??1; });
